latex = "lualatex"
source = "【特別演習】各論文と自己の研究の関係について.tex"

[programs.latex]
command = "lualatex"
opts = "-synctex=0"

[programs.bibtex]
command = "pbibtex"
target = "DB.bib"
opts = ["-kanji=utf8"]
args = "%B"