latex = "lualatex"
source = "【特別演習】周波数解析を用いたボットネット検出システムDeBotについて.tex"

[programs.latex]
command = "lualatex"
opts = "-synctex=0"

[programs.bibtex]
command = "pbibtex"
target = "DB.bib"
opts = ["-kanji=utf8"]
args = "%B"
