latex = "lualatex"
source = "【実験】LombScargleピリオドグラムによるBOS2016の解析.tex"

[programs.latex]
command = "lualatex"
opts = "-synctex=0"

[programs.bibtex]
command = "pbibtex"
target = "DB.bib"
opts = ["-kanji=utf8"]
args = "%B"
